/*
   This file was generated automatically by Alchitry Labs version 1.2.0.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module switch_1 (
    input x,
    input y,
    input z,
    output reg a,
    output reg b,
    output reg c
  );
  
  
  
  always @* begin
    a = x;
    b = y;
    c = z;
  end
endmodule
